# Generated by Django 6.1.1 on 2026-09-17 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('sku', models.CharField(max_length=50)),
                ('spec_line', models.CharField(blank=True, max_length=300)),
                ('base_price_aed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('detected_width_mm', models.FloatField(blank=True, null=True)),
                ('detected_height_mm', models.FloatField(blank=True, null=True)),
                ('matched_size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('UNSUPPORTED', 'Unsupported')], default='UNSUPPORTED', max_length=20)),
                ('orientation', models.CharField(blank=True, choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], max_length=20)),
                ('is_valid', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('quoted_price_aed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.PositiveIntegerField(default=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.product')),
            ],
        ),
    ]
