# Generated by Django 6.1.1 on 2026-09-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkupload',
            name='matched_size',
            field=models.CharField(choices=[('A6', 'A6'), ('B6', 'B6'), ('A5', 'A5'), ('B5', 'B5'), ('A4', 'A4'), ('B4', 'B4'), ('A3', 'A3'), ('B3', 'B3'), ('UNSUPPORTED', 'Unsupported')], default='UNSUPPORTED', max_length=20),
        ),
    ]
