# Generated by Django 6.1.1 on 2026-09-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_artworkupload_matched_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkupload',
            name='bleed_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artworkupload',
            name='pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='artworkupload',
            name='sides',
            field=models.CharField(blank=True, choices=[('single', 'Single side'), ('double', 'Front and Back')], max_length=10),
        ),
        migrations.AddField(
            model_name='artworkupload',
            name='trim_source',
            field=models.CharField(blank=True, choices=[('trimbox', 'TrimBox'), ('mediabox', 'MediaBox'), ('mediabox_minus_bleed', 'MediaBox minus bleed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='artworkupload',
            name='matched_size',
            field=models.CharField(choices=[('A6', 'A6'), ('B6', 'B6'), ('DL', 'DL'), ('A5', 'A5'), ('B5', 'B5'), ('A4', 'A4'), ('B4', 'B4'), ('A3', 'A3'), ('B3', 'B3'), ('UNSUPPORTED', 'Unsupported')], default='UNSUPPORTED', max_length=20),
        ),
    ]
