# Generated by Django 6.1.1 on 2026-09-18 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_flyer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price_aed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('pricing_role', models.CharField(choices=[('base', 'Base'), ('uplift', 'Uplift'), ('none', 'None')], default='none', max_length=10)),
                ('yield_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orders.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('product', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('label_en', models.CharField(max_length=100)),
                ('label_ar', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('integer_value', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.FloatField(blank=True, null=True)),
                ('height_mm', models.FloatField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('uplift_percent', models.FloatField(blank=True, null=True)),
                ('cutoff_time', models.TimeField(blank=True, null=True)),
                ('working_day_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='orders.option')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('option', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fils', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='orders.product')),
                ('values', models.ManyToManyField(related_name='base_prices', to='orders.optionvalue')),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_en', models.CharField(max_length=200)),
                ('reason_ar', models.CharField(blank=True, max_length=200)),
                ('value_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_as_x', to='orders.optionvalue')),
                ('value_y', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_as_y', to='orders.optionvalue')),
            ],
            options={
                'unique_together': {('value_x', 'value_y')},
            },
        ),
    ]
