# Generated by Django 6.1.1 on 2026-09-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_seed_flyers_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='delivery_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='delivery_window_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
