# Generated by Django 6.1.1 on 2026-09-18 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_seed_turnaround_delivery_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bleed_max_mm',
            field=models.FloatField(default=6.0, help_text="Largest uniform bleed inferred when a file has no TrimBox and its page size doesn't exactly match a Size value."),
        ),
        migrations.AddField(
            model_name='product',
            name='bleed_min_mm',
            field=models.FloatField(default=1.0, help_text="Smallest uniform bleed inferred when a file has no TrimBox and its page size doesn't exactly match a Size value."),
        ),
        migrations.AddField(
            model_name='product',
            name='bleed_mm',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='product',
            name='safe_mm',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_tolerance_mm',
            field=models.FloatField(default=1.5, help_text='Detected trim size must be within this many mm of a Size value, on each axis, in either orientation.'),
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('front', 'Front'), ('back', 'Back')], max_length=10)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('source_page_count', models.PositiveIntegerField(default=0)),
                ('page_index', models.PositiveIntegerField(default=1)),
                ('trim_width_mm', models.FloatField(blank=True, null=True)),
                ('trim_height_mm', models.FloatField(blank=True, null=True)),
                ('media_width_mm', models.FloatField(blank=True, null=True)),
                ('media_height_mm', models.FloatField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], max_length=20)),
                ('trim_source', models.CharField(blank=True, choices=[('trimbox', 'TrimBox'), ('crop', 'CropBox'), ('media', 'MediaBox'), ('media_minus_bleed', 'MediaBox minus bleed')], max_length=30)),
                ('bleed_mm', models.FloatField(blank=True, null=True)),
                ('rotation', models.PositiveIntegerField(default=0)),
                ('is_valid', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=30)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('matched_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_artworks', to='orders.optionvalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='orders.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ArtworkUpload',
        ),
    ]
