# Generated by Django 6.1.1 on 2026-09-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_designrequest_designrequestfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='preflight_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='ppi_error_below',
            field=models.FloatField(default=150.0, help_text='Effective image ppi below this is a Preflight Error (low_ppi).'),
        ),
        migrations.AddField(
            model_name='product',
            name='ppi_warn_below',
            field=models.FloatField(default=250.0, help_text='Effective image ppi below this (and at/above ppi_error_below) is a Preflight Warning (low_ppi).'),
        ),
    ]
