# Generated by Django 6.1.1 on 2026-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_artwork_preflight_report_product_ppi_error_below_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='page_image',
            field=models.ImageField(blank=True, upload_to='renders/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='renders/%Y/%m/%d/'),
        ),
    ]
