# Generated by Django 6.1.1 on 2026-09-18 15:15

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_artwork_page_image_artwork_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('token', models.CharField(default=orders.models.generate_order_token, editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('address_line', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash/card on delivery')], default='cod', max_length=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('status', models.CharField(choices=[('staff_check', 'Staff check'), ('in_production', 'In production'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered')], max_length=20)),
                ('browsing_language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=10)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_snapshot', models.JSONField(default=list)),
                ('base_fils', models.PositiveIntegerField()),
                ('subtotal_fils', models.PositiveIntegerField()),
                ('vat_fils', models.PositiveIntegerField()),
                ('total_fils', models.PositiveIntegerField()),
                ('uplifts_snapshot', models.JSONField(default=list)),
                ('same_as_front', models.BooleanField(default=False)),
                ('size_choice', models.JSONField(blank=True, default=dict)),
                ('preflight_report_snapshot', models.JSONField(default=dict)),
                ('accepted_warning_codes', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField()),
                ('promised_date', models.DateField()),
                ('promised_window_start', models.TimeField(blank=True, null=True)),
                ('promised_window_end', models.TimeField(blank=True, null=True)),
                ('back_artwork', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.artwork')),
                ('front_artwork', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.artwork')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('staff_check', 'Staff check'), ('in_production', 'In production'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered')], max_length=20)),
                ('staff_user', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
