# Generated by Django 6.1.1 on 2026-09-19 09:09

from django.db import migrations

LEGACY_SLUG = "flyer-glossy-170gsm"


def remove_legacy_flyer_product(apps, schema_editor):
    """The first-draft per-paper flyer product (migration 0004) has no Options and
    cannot be ordered; the generic `flyers` product replaced it. Kept if any Order
    line still points at it (PROTECT), which can't happen for a product with no
    Options but is cheap to be safe about."""
    Product = apps.get_model("orders", "Product")
    OrderLine = apps.get_model("orders", "OrderLine")
    if OrderLine.objects.filter(product__slug=LEGACY_SLUG).exists():
        return
    Product.objects.filter(slug=LEGACY_SLUG).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_orderline_orderstatuschange'),
    ]

    operations = [
        migrations.RunPython(remove_legacy_flyer_product, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='base_price_aed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_line',
        ),
    ]
