# Generated by Django 6.1.1 on 2026-09-19 09:13

from django.db import migrations, models


def backfill_turnaround(apps, schema_editor):
    OrderLine = apps.get_model("orders", "OrderLine")
    for line in OrderLine.objects.all():
        for entry in line.configuration_snapshot:
            if entry.get("option") == "turnaround":
                line.turnaround = entry.get("value", "")
                line.save(update_fields=["turnaround"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_drop_legacy_product_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='turnaround',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.RunPython(backfill_turnaround, migrations.RunPython.noop),
    ]
