# Generated by Django 6.1.1 on 2026-09-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_seed_flyers_arabic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash/card on delivery')], default='cod', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='base_fils',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='subtotal_fils',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='total_fils',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='vat_fils',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
