# Generated by Django 6.1.1 on 2026-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_money_and_address_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='upload_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
