# Generated by Django 6.1.1 on 2026-09-19 11:25

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_artwork_upload_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sources/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('page_count', models.PositiveIntegerField()),
                ('pages', models.JSONField(default=list)),
                ('upload_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=orders.models._source_expiry)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='orders.product')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='orders.sourcefile'),
        ),
    ]
